const doctors=[
 {name:'周文远',title:'主任医师 · 中医内科',specialty:'脾胃调理 · 睡眠障碍 · 情志疾病',initial:'周'},
 {name:'沈知微',title:'主治医师 · 针灸推拿',specialty:'颈肩腰背痛 · 针灸调理 · 体态平衡',initial:'沈'},
 {name:'苏青禾',title:'主治医师 · 妇儿调养',specialty:'女性调理 · 小儿体质 · 四季养生',initial:'苏'}
];
const grid=document.querySelector('#doctorGrid'), select=document.querySelector('#doctorSelect');
doctors.forEach((d,i)=>{grid.insertAdjacentHTML('beforeend',`<article class="doctor-card"><span class="doctor-num">0${i+1}</span><div class="portrait" aria-hidden="true"></div><h3>${d.name}</h3><p>${d.title}</p><button class="doctor-book" data-doctor="${d.name}">预约此医师　→</button></article>`);select.insertAdjacentHTML('beforeend',`<option value="${d.name}">${d.name} · ${d.title.split(' · ')[1]}</option>`)});
const dates=['今天\n9/26','明天\n9/27','周日\n9/28','周一\n9/29','周二\n9/30'];
const dateRow=document.querySelector('#dateRow');dates.forEach((x,i)=>{let [a,b]=x.split('\n');dateRow.insertAdjacentHTML('beforeend',`<button type="button" class="date-btn ${i===1?'active':''}" data-date="${a}"><b>${a}</b><small>${b}</small></button>`)});
const timeGrid=document.querySelector('#timeGrid');['09:00','09:30','10:00','10:30','14:00','14:30','15:00','15:30'].forEach((t,i)=>timeGrid.insertAdjacentHTML('beforeend',`<button type="button" class="time-btn ${i===2?'disabled':i===1?'selected':''}" ${i===2?'disabled':''}>${t}</button>`));
document.addEventListener('click',e=>{const date=e.target.closest('.date-btn');if(date){document.querySelectorAll('.date-btn').forEach(x=>x.classList.remove('active'));date.classList.add('active')}const time=e.target.closest('.time-btn');if(time&&!time.disabled){document.querySelectorAll('.time-btn').forEach(x=>x.classList.remove('selected'));time.classList.add('selected')}const book=e.target.closest('.doctor-book');if(book){select.value=book.dataset.doctor;document.querySelector('#booking').scrollIntoView({behavior:'smooth'})}});
const dialog=document.querySelector('#patientDialog'), apptDialog=document.querySelector('#appointmentsDialog');
document.querySelector('#bookingForm').addEventListener('submit',e=>{e.preventDefault();const doctor=select.value,date=document.querySelector('.date-btn.active').dataset.date,time=document.querySelector('.time-btn.selected').textContent;document.querySelector('#confirmationText').innerHTML=`您已预约 <b>${doctor} 医师</b><br>${date} ${time} · ${document.querySelector('#serviceSelect').value}<br>确认短信将发送至您的手机。`;dialog.showModal()});
document.querySelector('#myAppointments').onclick=()=>apptDialog.showModal();document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('dialog').close());
const admin=document.querySelector('#adminApp'), patient=document.querySelector('#patientApp'), footer=document.querySelector('footer');
document.querySelector('#adminEntry').onclick=()=>{patient.classList.add('hidden');footer.classList.add('hidden');admin.classList.remove('hidden');window.scrollTo(0,0)};document.querySelector('#exitAdmin').onclick=()=>{admin.classList.add('hidden');patient.classList.remove('hidden');footer.classList.remove('hidden')};
const rows=[['09:00','陈静怡','周文远','初诊 · 中医内科','已确认'],['09:30','王　磊','周文远','复诊 · 调理随访','已确认'],['10:00','刘晓曼','沈知微','针灸调理','待确认'],['14:30','赵文博','苏青禾','妇科调养','已确认']];
function overview(){return `<section class="metrics"><div class="metric"><p>今日预约</p><strong>18</strong><small>↑ 较昨日 +12.5%</small></div><div class="metric"><p>今日到诊</p><strong>12</strong><small>已完成 66.7%</small></div><div class="metric"><p>待确认预约</p><strong>3</strong><small>需及时跟进</small></div><div class="metric"><p>本月取消率</p><strong>4.8%</strong><small>↓ 较上月 -1.2%</small></div></section><section class="admin-grid"><div class="panel"><div class="panel-head"><h2>今日预约</h2><button data-panel="appointments">查看全部 →</button></div>${table(rows)}</div><div class="panel"><div class="panel-head"><h2>医师出诊</h2><button data-panel="schedule">排班管理 →</button></div><ul class="schedule-list">${doctors.map((d,i)=>`<li><span class="mini-avatar">${d.initial}</span><div><strong>${d.name} · ${d.title.split(' · ')[1]}</strong><small>${i===2?'14:00 — 18:00':'09:00 — 12:00，14:00 — 18:00'}　·　${[6,5,4][i]} 个预约</small></div></li>`).join('')}</ul></div></section>`}
function table(data){return `<table class="table"><thead><tr><th>时间</th><th>患者</th><th>预约医师</th><th>项目</th><th>状态</th></tr></thead><tbody>${data.map(r=>`<tr>${r.slice(0,4).map(x=>`<td>${x}</td>`).join('')}<td><span class="pill ${r[4]==='待确认'?'wait':''}">${r[4]}</span></td></tr>`).join('')}</tbody></table>`}
function listPanel(name){const data=name==='patients'?rows.map((r,i)=>[r[1],['136 **** 2281','187 **** 1094','138 **** 8870','156 **** 5421'][i],r[3],i===0?'复诊患者':'初诊患者','查看档案']):rows;return `<section class="admin-table-panel"><div class="panel-head"><h2>${name==='patients'?'患者档案':'预约管理'}</h2><button class="add-btn">+ 新建预约</button></div><div class="toolbar"><input class="search" placeholder="搜索姓名、手机号或预约编号"><span style="font-size:12px;color:#78867e">共 ${data.length} 条记录</span></div>${name==='patients'?`<table class="table"><thead><tr><th>患者</th><th>联系电话</th><th>最近就诊项目</th><th>患者类型</th><th></th></tr></thead><tbody>${data.map(r=>`<tr>${r.map((x,i)=>`<td>${i===4?`<button class="text-btn">${x}</button>`:x}</td>`).join('')}</tr>`).join('')}</tbody></table>`:table(data)}</section>`}
function recordsPanel(){return `<section class="admin-table-panel"><div class="panel-head"><h2>病历与处方</h2><button class="add-btn">+ 新建病历</button></div><div class="toolbar"><input class="search" placeholder="搜索患者姓名或病历编号"><span style="font-size:12px;color:#78867e">仅限授权医师访问</span></div><table class="table"><thead><tr><th>病历编号</th><th>患者</th><th>接诊医师</th><th>就诊日期</th><th>处方状态</th></tr></thead><tbody><tr><td>BC-202609-018</td><td>陈静怡</td><td>周文远</td><td>2026-09-26</td><td><span class="pill">已开方</span></td></tr><tr><td>BC-202609-017</td><td>王 磊</td><td>周文远</td><td>2026-09-26</td><td><span class="pill">已开方</span></td></tr><tr><td>BC-202609-016</td><td>李梦然</td><td>沈知微</td><td>2026-09-25</td><td><span class="pill wait">待补充</span></td></tr></tbody></table></section>`}
function empty(name){return `<section class="empty-panel"><div class="modal-icon">✦</div><h2>${name}正在完善中</h2><p>当前可在工作台查看今日排班与预约信息。</p></section>`}
const content=document.querySelector('#adminContent');function render(panel='overview'){const titleMap={overview:'上午好，林雅',appointments:'预约管理',schedule:'排班管理',patients:'患者档案',doctors:'医师管理',services:'诊疗项目',records:'病历与处方',logs:'操作日志'};document.querySelector('#adminTitle').textContent=titleMap[panel];document.querySelector('#adminCrumb').textContent=panel==='overview'?'工作台':'诊疗运营 / '+titleMap[panel];content.innerHTML=panel==='overview'?overview():['appointments','patients','records'].includes(panel)?(panel==='records'?recordsPanel():listPanel(panel)):empty(titleMap[panel]);document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.side-link').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.panel));render(b.dataset.panel)})}render();
